@startditaa
+----+             +----+
|cRED| Líderes     |c33F| Réplicas
+----+             +----+

                        +---------+
          Escrita       |         |
         +--------------| Cliente |
         |              |         |
         |              +---------+
         v
 +---Broker 1---+        +---Broker 2---+        +---Broker 3---+
 |              |        |              |        |              |
 |/------------\|        |/------------\|        |/------------\|
 ||cRED        ||Réplica ||c33F        ||        ||c33F        ||
 || Partição 0 ||------->|| Partição 0 ||   +--> || Partição 0 ||
 ||            ||---+    ||            ||   |    ||            ||
 |\------------/|   |    |\------------/|   |    |\------------/|
 |/------------\|   |    |/------------\|   |    |/------------\|
 ||c33F        ||   |    ||cRED        ||   |    ||c33F        ||
 || Partição 1 ||   |    || Partição 1 ||   |    || Partição 1 ||
 ||            ||   |    ||            ||   |    ||            ||
 |\------------/|   |    |\------------/|   |    |\------------/|
 |/------------\|   |    |/------------\|   |    |/------------\|
 ||c33F        ||   |    ||c33F        ||   |    ||cRED        ||
 || Partição 2 ||   |    || Partição 2 ||   |    || Partição 2 ||
 ||            ||   |    ||            ||   |    ||            ||
 |\------------/|   |    |\------------/|   |    |\------------/|
 +--------------+   |    +--------------+   |    +--------------+
                    |                       |
                    +-----------------------+
                          Réplica
@endditaa