@startuml
scale 1024*768
UI --> "Session-Command": Envia mensagem de atulização
"Session-Command" --> "Session-Command": Validações e regras de negocios
"Session-Command" --> UI: Envia uma mensagem HTTP Ok (200)
"Session-Command" --> KAFKA: Escreve a mensagem em uma lista
KAFKA --> "Session-Worker": Envia comando
"Session-Worker" --> Datomic: escreve historico
"Session-Worker" --> Mongo: atualiza dado completo
newpage
scale 1024*768
UI --> "Session-Command": GET /api/session/{session-id}
"Session-Command" --> Mongo: Busca pela informacao
"Session-Command" <-- Mongo: Informação completa
"Session-Command" --> UI: Parse infomação para o usuarios
@enduml