@startditaa
                                       +----------------------+
                                       |                      |
                                       v                      |
+------------------+            /-------------\               |
|Dados Estruturados|----------->|             |         /--------------+-----------------\
+------------------+            |             |         | Transações   | CRM, ERP,       |
                                |             |-------->| e Interações | WEB, Mobile,    |
+------------------+            |             |         | de negócio   | Pontos de Vendas|
|  Arquivos de Log |----------->|             |         \--------------+-----------------/
+------------------+            |             |
                                |             |
+------------------+            |  Plataforma |
|  Dados de Escape |----------->|   Hadoop    |
+------------------+            |             |
                                |             |
+------------------+            |             |
|  Mídias Sociais  |----------->|             |
+------------------+            |             |
                                |             |
+------------------+            |             |
|Dispositivos e    |----------->|             |
|Sensores          |            |             |
+------------------+            |             |          /--------------+--------------\
                                |             |          | Business     | Dashboards,  |
/------------------\            |             |--------->| Intelligence,| Relatórios,  |
|                  |----------->|             |          | e Analytics  | Visualização |
|Bancos de Dados{s}|            |             |          \--------------+--------------/
\---+--------------/            \-------------/                |
                                       ^                       |
                                       |                       |
                                       +-----------------------+
@endditaa

